### ISSUE TITLE
Error to fix?

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/wheretolive.it#6]
vendor.f217bdd0.js:4 Uncaught Error: [$injector:modulerr] Failed to instantiate module wheretoliveApp due to:
Error: [$injector:modulerr] Failed to instantiate module elasticui due to:
Error: [$injector:nomod] Module 'elasticui' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.20/$injector/nomod?p0=elasticui
    at http://wheretolive.it/scripts/vendor.f217bdd0.js:3:22587
    at http://wheretolive.it/scripts/vendor.f217bdd0.js:3:30955
    at b (http://wheretolive.it/scripts/vendor.f217bdd0.js:3:30527)

**Comment by fabiofumarola** [comment]
ogni volta che faccio la build non va mai

**Comment by fabiofumarola** [comment]
1. il file elastcui.min.js viene copiato nella cartella dist/dist
2. non viene pacckettizzato con tutto il resto e quindi non trovato

workaround
1. copiato a mano il file dentro scripts
2. aggiunto a mano referenza in index.html
